### ISSUE TITLE
gpu_set_up

### ISSUE THREAD

**Issue by Eavis** [Eavis/CNN#2]

**Comment by Eavis** [comment]
http://caffe.berkeleyvision.org/install_apt.html
sudo apt install caffe-cpu
sudo apt build-dep caffe-cpu        # dependencies for CPU-only version

It requires a deb-src line in your sources.list. Continue with compilation.

**Comment by Eavis** [comment]
install opencv3

Guide is taken from http://www.pyimagesearch.com/2015/07/20/install-opencv-3-0-and-python-3-4-on-ubuntu/

Checkout and compile
git clone https://github.com/opencv/opencv
cd opencv
mkdir build
cd build
cmake ..
make
sudo make install

**Comment by Eavis** [comment]
https://stackoverflow.com/questions/51326713/where-are-caffe-libraries-for-sudo-apt-get-install-caffe-cpu-ubuntu-18

**Comment by Eavis** [comment]
pip3 install pandas, numpy, tensorflow, scipy

**Comment by Eavis** [comment]
sudo apt install caffe-cuda

https://github.com/dungba88/caffe-python3-install/blob/master/install-caffe.md

**Comment by Eavis** [comment]
pip3 install https://files.pythonhosted.org/packages/8c/52/33d739bcc547f22c522def535a8da7e6e5a0f6b98594717f519b5cb1a4e1/torchvision-0.1.8-py2.py3-none-any.whl

**Comment by Eavis** [comment]
Python 3.6.6 (default, Sep 12 2018, 18:26:19) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import caffe
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(.:21659): Gdk-CRITICAL **: 14:26:38.561: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(.:21659): Gdk-CRITICAL **: 14:26:38.562: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
>>> import numpy as np
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pandas/__init__.py", line 57, in <module>
    from pandas.io.api import *
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pandas/io/api.py", line 19, in <module>
    from pandas.io.packers import read_msgpack, to_msgpack
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pandas/io/packers.py", line 69, in <module>
    from pandas.util._move import (
ValueError: module functions cannot set METH_CLASS or METH_STATIC
>>>

**Comment by Eavis** [comment]
For me it seems to be matplotlib that causes this. If you want to run totally headless at the top of your script you can also try:

import matplotlib 
matplotlib.use('Agg') 
Which will tell matplotlib not to try to load up GTK.

**Comment by Eavis** [comment]
sudo pip uninstall matplotlib
sudo apt-get install python-matplotlib

use python-matplotlib can solve the problom.
