### ISSUE TITLE
render_blender

### ISSUE THREAD

**Issue by Eavis** [Eavis/CNN#4]

**Comment by Eavis** [comment]
followed the post of https://blender.stackexchange.com/questions/2078/how-to-use-blender-command-lines-in-osx
/Applications/Blender/blender.app/Contents/Resources/2.79/python

blender is bundled with python2.7

**Comment by Eavis** [comment]
python /Users/txl0524/Documents/RenderForCNN/demo_render/render_class_view.py -a 0.0 -e 10.0 -t 0.0 -d 3.0 -o /Users/txl0524/Documents/RenderForCNN/demo_render/demo_images/chair001/demo_img.png
blender /Users/txl0524/Documents/RenderForCNN/render_pipeline/blank.blend --background --python /Users/txl0524/Documents/RenderForCNN/render_pipeline/render_model_views.py -- /Users/txl0524/Documents/RenderForCNN/demo_render/sample_model/model.obj xxx xxx /var/folders/ky/x8m8llwx7q3_fqzh9wn04z0m0000gn/T/tmpVMI1fh/view.txt /var/folders/ky/x8m8llwx7q3_fqzh9wn04z0m0000gn/T/tmpVMI1fh
sh: blender: command not found
render failed. render_cmd: blender /Users/txl0524/Documents/RenderForCNN/render_pipeline/blank.blend --background --python /Users/txl0524/Documents/RenderForCNN/render_pipeline/render_model_views.py -- /Users/txl0524/Documents/RenderForCNN/demo_render/sample_model/model.obj xxx xxx /var/folders/ky/x8m8llwx7q3_fqzh9wn04z0m0000gn/T/tmpVMI1fh/view.txt /var/folders/ky/x8m8llwx7q3_fqzh9wn04z0m0000gn/T/tmpVMI1fh
>> Displaying rendered image ...
Traceback (most recent call last):
  File "run_demo.py", line 54, in <module>
    im = Image.open(os.path.join(syn_images_folder, model_name, image_name))
  File "/usr/local/lib/python3.7/site-packages/PIL/Image.py", line 2609, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/txl0524/Documents/RenderForCNN/demo_render/demo_images/chair001/demo_img.png'

**Comment by Eavis** [comment]
blender:

/Applications/Blender/blender.app/Contents/MacOS/blender
